version: '3.4'
services:
  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'

  mysql:
    image: mysql:5.6.27
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
    container_name: vgang-auth-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
  app:
    command: gow run .
    build:
      context: ../../
      dockerfile: ./devops/local/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ../../:/app
    depends_on:
      - mysql
      - redis

  asynq:
    command: go run tasks/main/main.go
    build:
      context: ../../
      dockerfile: ./devops/local/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - redis

  asynqmon:
    image: hibiken/asynqmon
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDR: "redis:6379"

volumes:
  mysqldata: